import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Banner from '../Components/Banner'
import Flip from 'react-reveal/Flip';

export default function CV() {
  return (
    <div className="">
    <Head>
        <title>Anne D. Développeur Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
    <div className="container bg-white">
        <div className="row m-0">
            <div className="col d-flex justify-content-center">
                <Banner />
            </div>
        </div>
        <div className="row m-0 d-flex flex-column flex-md-row">
            <div className="col p-2">
                <form className="text-center rounded" id="contact_form">
                    <h2 className="pt-4">PARLONS-NOUS !</h2>
                    <input type="hidden" name="contact_number" />
                    <div className="">
                        <label htmlFor="name"></label>
                        <input className="form-control" type="text" name="user_name" id="name" placeholder="Votre nom" required />
                        <label htmlFor="email"></label>
                        <input className="form-control" type="email" name="user_email" id="email" placeholder="Votre adresse mail" required />
                    </div>
                    <div>
                        <label htmlFor="message"></label>
                        <textarea className="form-control" rows="5" name="message" id="message" placeholder="Votre message" required />
                    </div>
                    <button className='button_item button btn btn-outline-dark mt-3 mb-3 fw-bold' type="submit"><i className="bi bi-envelope-fill"></i> ENVOYER</button>
                </form>
            </div>
            <div className="col p-0 my-5 my-md-auto">
                <div className="">
                    <Image className={`${styles.image}`}
                        src="/images/contact.svg"
                        alt=""
                        width={500}
                        height={230} 
                        layout="responsive"
                        priority='true'
                    />
                </div>
            </div> 
        </div>
    </div>
    </main>
    </div>
  )
}
