import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../Components/Banner'
import Flip from 'react-reveal/Flip';

export default function Home() {
  return (
    <div>
    <Head>
        <title>Anne D. Développeur Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
        <div className="row m-0 justify-content-center text-center">
            <div className="col col-md-9 col-lg-9 p-0 bg-white">
            <Banner />
                <div className="w-75 mx-auto pt-5 pb-5">
                    <Image className={`${styles.image}`}
                        src="/images/laptop.png"
                        alt=""
                        width={500}
                        height={230} 
                        layout="responsive"
                        priority='true'
                    />
                </div>
                <Flip left>
                    <h1 className="text-center mt-5 fw-bold">Anne DENICOURT</h1>
                </Flip>
                <Flip right>
                    <h2 className="text-center fs-3">Développeur Web</h2>
                </Flip>
                <Link href="#section1"><button className="animate-bounce button-scroll mt-5 text-center"><i className="bi bi-arrow-down-circle-fill fs-1 p-2"></i></button></Link>
            </div>
        </div>

        <div className="row m-0 justify-content-center text-center" id="section1">
            <div className="col col-md-9 col-lg-9 p-0 position-relative bg-white pt-5">
            <Flip left>
                <h2 className="">Faisons connaissance...</h2>
                <div className="w-25 mx-auto pt-5 pb-5">
                    <Image className={`${styles.image}`}
                        src="/images/girl2.png"
                        alt=""
                        width={500}
                        height={325} 
                        layout="responsive"
                        priority='true'
                    />
                </div>
                <div className="p-4 col-8 mx-auto fs-5">
                    Développeuse web avec une appétence toute particulière pour le framework React.js, 
                    je me suis engagée dans cette voie professionnelle avant tout par passion. 
                    Quoi de plus grisant et de plus stimulant que de créer un site, de le faire fonctionner 
                    et de chercher des solutions lorsqu’un problème apparaît ? <br />
                    Une vraie révélation pour moi avec l’envie chaque jour d’en apprendre toujours davantage.<br />
                </div>
                <Link href="/qui-suis-je"><button className={`${styles.bouton} btn btn-lg btn-secondary mt-3`}>En savoir plus</button></Link>
                <Link href="#section2"><button className="animate-bounce button-scroll mt-5 text-center"><i className="bi bi-arrow-down-circle-fill fs-1 p-2"></i></button></Link>
            </Flip>
            </div>
        </div>

        <div className="row m-0 justify-content-center text-center" id="section2">
            <div className="col col-lg-9 p-0 bg-white pt-5">
            <Flip left>
                <h2 className="">Côté TECHNOS</h2>
                <div className="w-25 mx-auto pt-3 pb-5">
                    <Image className={`${styles.image}`}
                        src="/images/fauteuil.png"
                        alt=""
                        width={4000}
                        height={4000} 
                        layout="responsive"
                        priority='true'
                    />
                </div>

                <div class="row g-5 mx-5 mb-5 d-flex flex-row">
                    <div class="col">
                        <div class="card fs-5 shadow">
                            <div class="card-body">
                                <i class="bi bi-laptop fs-1"></i>
                                <h4 class="card-title mt-4 mb-5">FRONTEND</h4>                            
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>HTML/CSS</p>
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>JAVASCRIPT</p>
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>REACT/NEXT</p>
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>BOOTSTRAP</p>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card fs-5 shadow">
                            <div class="card-body">
                                <i className="bi bi-server fs-1"></i>
                                <h4 class="card-tittle mt-4 mb-5">BACKEND</h4>
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>NODE</p>
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>EXPRESS</p>
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>API REST</p>
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>MYSQL/MONGODB</p>
                            </div>
                        </div>
                    </div>
                </div>
                <Link href="/qui-suis-je"><button className={`${styles.bouton} btn btn-lg btn-secondary mt-3`}>En savoir plus</button></Link>
                <Link href="#section3"><button className="animate-bounce button-scroll mt-5 text-center"><i className="bi bi-arrow-down-circle-fill fs-1 p-2"></i></button></Link>
            </Flip>
            </div>
        </div>


        <div className="row m-0 justify-content-center text-center" id="section3">
            <div className="col col-lg-9 p-0 bg-white pt-5">
            <Flip left>
                <h2 className="">Côté PROJETS</h2>
                <div className="w-25 mx-auto pt-3 pb-5">
                    <Image className={`${styles.image}`}
                        src="/images/idea.png"
                        alt=""
                        width={500}
                        height={249} 
                        layout="responsive"
                        priority='true'
                    />
                </div>

                <div class="row g-5 mx-5 mb-5 d-flex flex-row">
                    <div class="col">
                        <div class="card fs-5 shadow">
                            <div class="card-body">
                                <i class="bi bi-laptop fs-1"></i>
                                <h4 class="card-title mt-4 mb-5">FRONTEND</h4>                            
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>HTML/CSS</p>
                                
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card fs-5 shadow">
                            <div class="card-body">
                                <i className="bi bi-server fs-1"></i>
                                <h4 class="card-tittle mt-4 mb-5">BACKEND</h4>
                                <p class="card-text"><i class="bi bi-plus-circle-dotted me-3"></i>NODE</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
                <Link href="/qui-suis-je"><button className={`${styles.bouton} btn btn-lg btn-secondary mt-3`}>En savoir plus</button></Link>
            </Flip>
            </div>
        </div>

        
        
    </main>
    </div>
  )
}
