import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Banner from "../Components/Banner";
import Modal from "react-bootstrap/Modal";
import { useState } from "react";
import Footer from "../Components/Footer";
import { diplomes, jobs, pro } from "../datas/dataList";

export default function CV() {
  const [showInfo, setShowInfo] = useState(false);
  const [showCV, setShowCV] = useState(false);

  const zoom = (type) => {
    if (type === "infography") {
      window.open("/images/Recruter Anne Denicourt.jpg", "_blank");
    } else {
      window.open("/images/CV.jpg", "_blank");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Anne D. Développeur Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container bg-white pb-5">
          <div className="row m-0">
            <div className="col d-flex justify-content-center">
              <div className={`${styles.menu}`}>
                <Banner />
              </div>
            </div>
          </div>
          <div className="row mx-0 mt-5 justify-content-center">
            <h2 className="mt-5 pt-3 text-center">FAISONS CONNAISSANCE...</h2>
            <div className="col col-lg-10">
              <div className="mt-4 fs-5 text-center">
                Formée par OpenClassRooms et également autodidacte, je fais
                preuve d’une grande capacité d’autonomie et de beaucoup de
                ténacité, qualités non négligeables dans le métier de
                développeur web. Je suis sensible à l’UX, mais aussi à l’UI et
                tout ce qui touche à l’aspect esthétique d’un site internet. Un
                site fonctionnel c’est parfait mais s’il est agréable à utiliser
                et à regarder, c’est encore mieux !
              </div>
            </div>
          </div>

          <div className="row mx-0 mx-md-4 d-flex flex-column flex-lg-row">
            <div className="col mx-auto p-0 pt-5 text-center">
              <div className="w-75 mx-auto shadow">
                <Image
                  className="border rounded "
                  onClick={() => zoom("infography")}
                  src="/images/Recruter Anne Denicourt.jpg"
                  alt="recruter Anne Denicourt développeur web"
                  width={1240}
                  height={3248}
                  layout="responsive"
                  priority="true"
                />
              </div>
              <div
                className="infos mt-3 me-4"
                onClick={() => setShowInfo(true)}
              >
                <i className="bi bi-search fs-4 me-2"></i>Zoom
              </div>
              <Modal show={showInfo} onHide={() => setShowInfo(false)}>
                <Modal.Body>
                  <img
                    src="/images/Recruter Anne Denicourt.jpg"
                    alt=""
                    width="1000"
                  />
                </Modal.Body>
              </Modal>
            </div>
            <div className="col mx-auto px-0 px-lg-2 pt-5 text-start">
              <h3 className="mb-5 text-center text-decoration-underline">
                PARCOURS PROFESSIONNEL
              </h3>
              <div className="pb-3">
                {jobs.map((job) => {
                  return (
                    <div key={`job-${job.id}`} className="mb-4">
                      <div className="fs-5 fw-bold text-uppercase">
                        <i className="bi bi-stop-fill me-2 fs-6 text-warning"></i>
                        {job.job}
                      </div>
                      <div className="ms-4">Entreprise : {job.society}</div>
                      {job.link && (
                        <a
                          className="ms-4"
                          href={`https://${job.link}`}
                          target="_blank"
                        >
                          {job.link}
                        </a>
                      )}
                      <div className="ms-4">Période : {job.period}</div>
                    </div>
                  );
                })}
              </div>
              <div
                className={`${styles.bg_card} mb-5 p-3 fs-5 fw-bold text-center border rounded shadow`}
              >
                Comme dans tout ce que j’entreprends, je crée un site internet
                avec le cœur en faisant appel à ma part créative, mon sens du
                graphisme et mon goût pour le travail bien fait de façon à
                satisfaire les attentes du client et ceux de l’utilisateur. Et
                j’adore ça !
              </div>
            </div>
          </div>
          <div className="row mx-0 pb-5 d-flex flex-column flex-lg-row">
            <div className="col col-lg-6 mx-auto pt-5 text-end">
              <h3 className="mb-5 text-end text-decoration-underline">
                DIPLÔMES
              </h3>
              <div>
                {diplomes.map((diplome) => {
                  return (
                    <div key={`diplome-${diplome.id}`} className="mb-4">
                      <i className="bi bi-stop-fill me-2 text-warning"></i>
                      <span className="fs-5 fw-bold text-uppercase">
                        {diplome.name}
                      </span>
                      {diplome.infos && (
                        <div className="fst-italic">{diplome.infos}</div>
                      )}
                      <div className="ms-4">{diplome.period}</div>
                    </div>
                  );
                })}
              </div>
            </div>
            <div className="col col-lg-6 mx-auto pt-5 text-center">
              <h3 className="mb-4 text-center text-decoration-underline">
                MON CV
              </h3>
              <div className="w-50 mx-auto shadow mb-3">
                <Image
                  className="rounded"
                  onClick={() => zoom("cv")}
                  src="/images/CV.jpg"
                  alt="CV Anne Denicourt développeur web"
                  width={1240}
                  height={1754}
                  layout="responsive"
                  priority="true"
                />
              </div>

              <span className="infos me-4" onClick={() => setShowCV(true)}>
                <i className="bi bi-search fs-4 me-2"></i>Zoom
              </span>
              <a className="text-dark" href="/images/CV.jpg" download>
                <i className="bi bi-download fs-4 me-2"></i> Télécharger
              </a>
              <Modal size="lg" show={showCV} onHide={() => setShowCV(false)}>
                <Modal.Body>
                  <img
                    src="/images/CV.jpg"
                    alt="CV Anne Denicourt développeur web"
                  />
                </Modal.Body>
              </Modal>
            </div>
            <div className="text-center">
              <Link href="/#contact">
                <button
                  className={`${styles.bouton} btn btn-lg btn-secondary mt-5`}
                >
                  Me contacter
                </button>
              </Link>
            </div>
          </div>
          <Footer />
        </div>
      </main>
    </div>
  );
}
