import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Banner from '../Components/Banner'

export default function CV() {
  return (
    <div className={styles.container}>
    <Head>
        <title>Anne D. Développeur Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
    <div className="row m-0 justify-content-center">
            <div className="col col-md-9 col-lg-9 p-0 position-relative bg-white">
            <Banner />
                <div className="w-50 mx-auto shadow mb-5">
                    <Image className="rounded"
                        src="/images/CV.jpg"
                        alt=""
                        width={1240}
                        height={1754} 
                        layout="responsive"
                        priority='true'
                    />
                </div>
                
            </div>
        </div>
    </main>
    </div>
  )
}
