import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../Components/Banner'
import CardProject from '../Components/CardProject'
import { projects } from '../datas/projectList'

export default function Portfolio() {

  return (
    <div>
    <Head>
        <title>Anne D. Développeur Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>

    <div className="container bg-white">
        <div className="row m-0">
            <div className="col d-flex justify-content-center">
                <Banner />
            </div>
        </div>
        <div className="row mx-auto mt-5 d-flex flex-column flex-md-row justify-content-center">
            {projects.map(project => (
                <div className="col col-md-5 mb-5 text-center" key={project.id}>
                    <CardProject 
                    id={project.id}
                    name={project.name}
                    title={project.title}
                    description={project.description}
                    techno={project.techno}
                    image={project.image}
                    link={project.link}
                    github={project.github}
                    />
                </div>
            ))}
        </div>
    </div>
    </main>
    </div>
  )
}
