import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../Components/Banner'
import CardTech from '../Components/CardTech'
import Flip from 'react-reveal/Flip';
import Fade from 'react-reveal/Fade';

export default function Home() {

  return (
    <div>
    <Head>
        <title>Anne D. Développeur Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
        <div className="row col-9 mx-auto justify-content-center text-center bg-white">
            <Banner />
            <div className="w-75 mx-auto pt-5 pb-5">
                <Image className={`${styles.image}`}
                    src="/images/laptop.png"
                    alt=""
                    width={500}
                    height={230} 
                    layout="responsive"
                    priority='true'
                />
            </div>
            <Flip left>
                <h1 className="text-center mt-5 fw-bold">Anne DENICOURT</h1>
            </Flip>
            <Flip right>
                <h2 className="text-center fs-3">Développeur Web</h2>
            </Flip>
        </div>


        
        
  );
        
    </main>
    </div>
  )
}
