import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Banner from '../Components/Banner'

export default function Presentation() {
  return (
    <div className={styles.container}>
    <Head>
        <title>Anne D. Développeur Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
        <div className="row m-0 justify-content-center d-flex flex-row">
            <div className="col col-md-9 col-lg-9 p-0 bg-white"><Banner /></div>
        </div>
        <div className="row m-0 justify-content-center">
            <div className="col col-md-9 col-lg-9 pb-5 bg-white d-lg-flex justify-content-center">
                <div className="col-8 col-lg-4 mx-auto mx-lg-3">
                    <div className="shadow">
                    <Image className="border rounded"
                        src="/images/Recruter Anne Denicourt.jpg"
                        alt=""
                        width={1240}
                        height={3248} 
                        layout="responsive"
                        priority='true'
                    />
                    </div>
                </div>
                <div className="col-8 col-lg-5 px-5 mx-auto mx-lg-0">
                    <h2 className="mt-5 mt-lg-0 mb-lg-5">Faisons connaissance...</h2>
                    <div className="">
                        Développeuse web avec une appétence toute particulière pour le framework React.js, 
                        je me suis engagée dans cette voie professionnelle avant tout par passion. 
                        Quoi de plus grisant et de plus stimulant que de créer un site, de le faire fonctionner 
                        et de chercher des solutions lorsqu’un problème apparaît ? <br />
                        Une vraie révélation pour moi avec l’envie chaque jour d’en apprendre toujours davantage.<br />
                        Formée par OpenClassRooms et également autodidacte, je fais preuve d’une grande capacité d’autonomie
                        et de beaucoup de ténacité, qualités non négligeables dans le métier de développeur web. <br />
                        Je suis sensible à l’UX, mais aussi à l’UI et tout ce qui touche à l’aspect esthétique d’un site internet.
                        Un site fonctionnel c’est parfait mais s’il est agréable à utiliser et à regarder, c’est encore mieux ! <br />
                        Outre ma grande expérience dans le monde de la communication et ma vie professionnelle riche et variée, c’est mon côté passionné qui pourrait me distinguer de la plupart des développeurs.
                        Comme dans tout ce que j’entreprends, je crée un site internet avec le cœur en faisant appel à ma part créative, mon sens du graphisme et mon goût pour le travail bien fait de façon à satisfaire les attentes du client et ceux de l’utilisateur.
                        Et j’adore ça !
                    </div>
                    <div className="w-50 mt-5 mx-auto pb-5">
                        <Image className={`${styles.image}`}
                            src="/images/girl2.png"
                            alt=""
                            width={500}
                            height={325} 
                            layout="responsive"
                            priority='true'
                        />
                    </div>
                </div>
            </div>
        </div>
    </main>
    </div>
  )
}
